AppBundle\Entity\Cubeslot:
    type: entity
    table: cubeslot
    manyToOne:
        cube:
            targetEntity: Cube
            nullable: false
            inversedBy: slots
            joinColumn:
                name: cube_id
                referencedColumnName: id
        card:
            targetEntity: Card
            nullable: false
            joinColumn:
                name: card_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: smallint
    lifecycleCallbacks: {  }
